/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#3f465c',
        secondary: '#565e74',
        'on-tertiary-fixed': '#001f28',
        'on-tertiary': '#ffffff',
        'primary-container': '#dc2626',
        'tertiary-container': '#007c99',
        'on-primary-container': '#fff6f5',
        error: '#ba1a1a',
        'on-secondary-fixed': '#131b2e',
        'surface-tint': '#bf0715',
        'outline-variant': '#e6bdb8',
        'primary-fixed': '#ffdad6',
        'on-secondary-container': '#5c647a',
        'on-tertiary-container': '#effaff',
        outline: '#916f6b',
        'inverse-on-surface': '#eaf1ff',
        'surface-container-highest': '#d3e4fe',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#ffb4ab',
        'on-tertiary-fixed-variant': '#004e61',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'inverse-primary': '#ffb4ab',
        'on-error': '#ffffff',
        'on-primary-fixed': '#410002',
        'tertiary-fixed-dim': '#6cd3f7',
        surface: '#f8f9ff',
        'on-background': '#0b1c30',
        'on-surface': '#0b1c30',
        background: '#f8f9ff',
        'on-surface-variant': '#5c403c',
        'surface-container-low': '#eff4ff',
        'secondary-fixed': '#dae2fd',
        'inverse-surface': '#213145',
        'surface-container': '#e5eeff',
        tertiary: '#006279',
        'surface-container-high': '#dce9ff',
        'secondary-fixed-dim': '#bec6e0',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#93000b',
        'surface-dim': '#cbdbf5',
        'surface-variant': '#d3e4fe',
        'on-primary': '#ffffff',
        primary: '#b70011',
        'surface-bright': '#f8f9ff',
        'secondary-container': '#dae2fd',
        'tertiary-fixed': '#b7eaff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      screens: {
        xs: '375px',
      },
      spacing: {
        margin: '2rem',
        'gutter-mobile': '1rem',
        gutter: '1.5rem',
        'space-xl': '2.5rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-2xl': '4rem',
        'space-xs': '0.25rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-tech': ['Inter', 'sans-serif'],
        'headline-xl-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'label-tech': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-xl-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'display-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '800' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.015em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
